image:
     file: .gitpod.dockerfile
ports:
  - port: 3000
tasks:
  - init: |
      mvn clean install -Pfatjar -f server/pom.xml -Dmaven.test.skip=true
      yarn --cwd client
  - command: |
      java -jar server/example/workflow-example/target/workflow-example-1.2.0-SNAPSHOT-glsp.jar com.eclipsesource.glsp.example.workflow.ExampleServerLauncher
  - command: |
      yarn --cwd client/examples/workflow/browser-app start --hostname=0.0.0.0 ../workspace
      